### ISSUE TITLE
First login

### ISSUE THREAD

**Issue by SaFi2266** [SaFi2266/facebook_app#1]
Hello,
After successful login with facebook, I got alerted "error" and this error message in console 

`[2017-05-14 04:08:56,864] ERROR in app: Exception on /users [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/tryman/public/fb/app.py", line 25, in store_email
    email = request.json[0]['email']
KeyError: 'email'
`

**Comment by rohanil** [comment]
This was related to FB account's email permission. After trying with the new account, it works properly. There is one more thing to do here which is unblocking third-party cookies and site data from browser settings. Thanks.
